services:
  cdroms:
    image: node:24
    working_dir: /opt/project
    volumes:
      # - PATH_TO_REPO:/opt/project
      - /home/mowibox/Documents/WorkspaceU/cdroms/cdroms-robotics.github.io:/opt/project
    ports:
      - "8080"
    entrypoint: [""]
    command: npm run dev
    stdin_open: true
    tty: true
    restart: "no"
